### ISSUE TITLE
なにつくるのー？

### ISSUE THREAD

**Issue by johnta0** [CryptocurrencyApp/CoinPocket#1]

**Comment by gatchan0807** [comment]
@johnta0 

こーゆーのつくりますー！
↓
https://github.com/CryptocurrencyApp/CryptocurrencyClient/wiki/%E4%BD%9C%E3%82%8B%E3%82%82%E3%81%AE%E3%81%AE%E6%A6%82%E8%A6%81

とりあえず2/16~18の学生作品展に向けて作品として作って、そのあとローンチしたいなって思ってる感じです！
