### ISSUE TITLE
ログイン前のHOME画面

### ISSUE THREAD

**Issue by r-miyamae** [CryptocurrencyApp/CoinPocket#10]
# wiki
https://github.com/CryptocurrencyApp/CoinPocket/wiki/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB#%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E5%89%8D

# 概要
- アプリの概要を記載
- ログインフォーム
- ユーザ登録へのリンク
- ロゴ

# 画面イメージ
![img_2101](https://user-images.githubusercontent.com/17544389/35320039-b98e8c2a-0125-11e8-9704-daf5df11b439.JPG)

**Comment by r-miyamae** [comment]
名前(ヘッダー): CoinPocket

**Comment by gatchan0807** [comment]
ユーザーIDを受け取ったら、
storageの中の `isLogin` をtrueにして、`userId` に受け取ったユーザーIDを保存する

**Comment by gatchan0807** [comment]
残るはログイン処理だけ

**Comment by gatchan0807** [comment]
DONE
