### ISSUE TITLE
コイン管理画面の実装

### ISSUE THREAD

**Issue by gatchan0807** [CryptocurrencyApp/CoinPocket#3]
# wiki
https://github.com/CryptocurrencyApp/CryptocurrencyClient/wiki/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB#%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88%E6%83%85%E5%A0%B1%E7%B7%A8%E9%9B%86

# 概要
ユーザーのアセット情報を登録・枚数編集・削除を行う画面

# 画面イメージ
![img_2093](https://user-images.githubusercontent.com/16623885/35193007-9ce3c5d8-fedf-11e7-951c-f0a5c2b39d62.jpg)

# 詳細

- 情報の追加・削除・編集は基本的に非同期通信を使用し、Submitボタン無しで登録できるようにする
- 登録フォームは `GET /coinIds` から取得した選択可能コイン銘柄の中から検索して登録する
- 編集フォーム（登録済みのコインリスト）は登録順で並ぶ
    - このため、登録フォームで選択し、登録したコインは編集フォームの一番上に0枚の状態でデータが挿入される

**Comment by gatchan0807** [comment]
@r-miyamae これの名前 `管理画面` のがいいよーな気がするんやけどどうやろう…？

**Comment by gatchan0807** [comment]
コイン銘柄追加フォームの実装
- 6e25ff6c2947d49af499dda1552dae7c67679f5a

コイン銘柄追加フォームのUIの調整
- 6a6fc28357bdddde42d808b9ced9d78601a79b6c

**Comment by r-miyamae** [comment]
#名前
- コイン管理

**Comment by gatchan0807** [comment]
@r-miyamae この画面実行ができてるか確認してもらってもいい？

**Comment by gatchan0807** [comment]
DONE
