### ISSUE TITLE
キャッチアップ画面の実装

### ISSUE THREAD

**Issue by gatchan0807** [CryptocurrencyApp/CoinPocket#4]
# wiki
https://github.com/CryptocurrencyApp/CryptocurrencyClient/wiki/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB#%E3%82%AD%E3%83%A3%E3%83%83%E3%83%81%E3%82%A2%E3%83%83%E3%83%97

# 概要
投稿された仮想通貨についての記事・アカウントのURLについて確認できる画面

# 画面イメージ
![img_2095](https://user-images.githubusercontent.com/16623885/35193299-dba941a4-fee3-11e7-8cef-4406085c3df3.jpg)

# 詳細

- 一つの投稿をカードとして表示する
    - サイトサムネイルはリンク先のOGPで設定された画像を表示し、存在しない場合は適当に作った "No Images." の画像を表示する
    - 高評価・低評価のバーを表示し、それぞれの評価数を数字でバーの上に表示する
- ソートボタンは 新着順（新しい順/古い順）・高評価順の３つをラウンドロビンで切り替える
- 新規投稿ボタンから情報投稿画面へ遷移する
- （将来的に投稿削除ボタンをカードに追加する）

**Comment by r-miyamae** [comment]
mockサーバのレスポンスがuserに関する情報抜けてるので足す

**Comment by r-miyamae** [comment]
名前: キャッチアップ
