### ISSUE TITLE
投稿画面の実装

### ISSUE THREAD

**Issue by gatchan0807** [CryptocurrencyApp/CoinPocket#5]
# wiki
https://github.com/CryptocurrencyApp/CryptocurrencyClient/wiki/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB#%E6%83%85%E5%A0%B1%E6%8A%95%E7%A8%BF

# 概要
キャッチアップ画面に表示する見ておけ情報を登録する画面

# 画面イメージ
![img_2096](https://user-images.githubusercontent.com/16623885/35194804-b142f482-fefc-11e7-8699-f21e1a561b74.jpg)

# 詳細

- 文字数カウンタを用意する（100文字で赤文字化して、送信不可にする）
- XSS対策とかセキュリティ面（出来れば）
- `POST /articles` に対してデータ送信を行う（ https://github.com/CryptocurrencyApp/CryptocurrencyClient/wiki/Mockサーバーについて#post-articles ）

**Comment by r-miyamae** [comment]
名前： 投稿
