### ISSUE TITLE
ログイン後のHome画面の実装

### ISSUE THREAD

**Issue by gatchan0807** [CryptocurrencyApp/CoinPocket#8]
# wiki
https://github.com/CryptocurrencyApp/CoinPocket/wiki/%E7%94%BB%E9%9D%A2%E9%81%B7%E7%A7%BB#%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E5%BE%8C

# 概要
ユーザーが必要としている情報にアクセスしやすい要素を配置する

# 画面イメージ
![img_2100](https://user-images.githubusercontent.com/16623885/35319781-b556e07c-0124-11e8-9732-eed81e52dec7.JPG)

# 詳細

- 所持しているコインの価格一覧を表示する
- アセット情報確認画面へのアクセス方法を提供する
- キャッチアップ画面へのアクセス方法を提供する

**Comment by r-miyamae** [comment]
名前: HOME

**Comment by gatchan0807** [comment]
TODO: ネットワークエラー表示を出来るようにする

**Comment by gatchan0807** [comment]
@r-miyamae 同じように動作確認してもらってもいい？

**Comment by gatchan0807** [comment]
DONE
